---
- name: Create Swift api -> Ceph rgw bridge
  hosts: localhost
  connection: local
  vars:
    radosgw_frontend_port: 8080

  tasks:
    - name: Include environments/kolla/secrets.yml
      include_vars:
        file: /opt/configuration/environments/kolla/secrets.yml

    - name: Create swift service account
      os_user:
        cloud: admin
        state: present
        name: swift
        password: "{{ swift_keystone_password }}"
        domain: default
        default_project: service

    - name: Add admin role to swift service account
      os_user_role:
        cloud: admin
        state: present
        user: swift
        role: admin
        project: service

    - name: Create swift service
      os_keystone_service:
        cloud: admin
        state: present
        name: swift
        service_type: object-store
        description: Openstack Object Storage

    - name: Create swift admin,internal endpoints
      os_keystone_endpoint:
        cloud: admin
        state: present
        service: swift
        endpoint_interface: "{{ item }}"
        url: "http://api-int.betacloud.host:{{ radosgw_frontend_port }}/swift/v1/AUTH_%(tenant_id)s"
        region: RegionOne
      loop:
        - admin
        - internal

    - name: Create swift public endpoint
      os_keystone_endpoint:
        cloud: admin
        state: present
        service: swift
        endpoint_interface: public
        url: "https://api.betacloud.host:{{ radosgw_frontend_port }}/swift/v1/AUTH_%(tenant_id)s"
        region: RegionOne
